### PR TITLE
Dont fail on missing package.json

### LINKED ISSUE #312: WebApi doesn't work in projects that use Webpack
### Environment
Node version: v8.9.1
Npm version: 6.9.0
OS and version: Windows 10.0.17134.0
azure-devops-node-api version: 8.0.0

### Issue Description
The WebApi class' constructor tries to read the caller's package.json using `readFileSync`:
```
// WebApi.js, line 148
const nodeApiVersion = JSON.parse(fs.readFileSync(path.resolve(__dirname, 'package.json'), 'utf8')).version;
```
This causes an exception when using Webpack to build and bundle, because the build output folder is an arbitrary `dist` folder, not the project root, as the constructor is expecting. Furthermore, it is a bad practice to do this kind of logic in a constructor. Constructors should be one of the most reliable routines, not making calls that depend on the environment.

### Expected behaviour
Using WebApi should work in projects that are build with Webpack (or any other bundler that makes using __dirname unreliable).

### Actual behaviour
Instantiating a WebApi object fails

### Steps to reproduce
1. Install azure-devops-node-api 8.0.0 in a project that uses Webpack to build
2. Try to create an instance of WebApi

### PR DESCRIPTION
**Pull request by damccorm**
When people use webpack, the releative location of files gets moved around - this makes sure we don't fail on that since its only used for userAgents. I think we technically have that as telemetry, but I've never seen us use it

Fixes #312

### CODE REVIEW

File: api/WebApi.ts [hunk 1]
```diff
@@ -145,7 +145,10 @@ export class WebApi {
                 userAgent = `${nodeApiName} (${window.navigator.userAgent})`;
             }
         } else {
-            const nodeApiVersion: string = JSON.parse(fs.readFileSync(path.resolve(__dirname, 'package.json'), 'utf8')).version;
+            let nodeApiVersion: string = 'unknown';
+            if (fs.existsSync(path.resolve(__dirname, 'package.json'))) {
```
Comment (jtpetty) [inline api/WebApi.ts]: any reason not to do
```
var packageFile = path.resolve(__dirname, 'package.json')
```
And use that in the exists and read calls?

Also, would it be better to not do the exists check and just do the read/parse inside a try/catch? There are other reasons you might not be able to read the package.json file. Do we still want to blow up on those?

Comment (damccorm) [reply api/WebApi.ts]: Updated to use a variable. What could cause us to fail to read the package.json file if it exists? All I can think of is that the file didn't get copied correctly, or permissions issues, either of which probably are going to cause other issues - I don't love silently not throwing on other stuff because I think the most likely thing that could cause is us missing something getting messed up on our end - otherwise I don't see any issues coming here.

Comment (jtpetty) [reply api/WebApi.ts]: permission issues was mainly what I was thinking of. I'm fine blowing up in that case, because you are right, if it exists and we can't read it, it probably means things later down the line will blow up as well.
